### PR TITLE
feat:(UI) basic page structure

### PR DESCRIPTION
**Pull request by blessedjasonmwanza**
## feat:(UI) basic page structure
In this User Interface update;
- Setup Gitflow and Github flow
- Create an npm project with webpack
- Build basic HTML & CSS UI
- Render Sample Scored dynamically using es6 modules

### CODE REVIEW

**Review by o-rashad — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

Hi @blessedjasonmwanza 👋😄, I'm Omar and i will be your reviewer for this project 😊

Good job so far!👌😃

There are some issues 🐞 that you still need to work on to go to the next project but you are almost there! 🏁🏁🏁


Your app directory should be something like this
```code
app-root-directory
  |- package.json
  |- webpack.config.js
  |- /dist
    |- bundle.js or be main.js
    |- index.html
  |- /src
   |- style.css
   |- index.js
```
Currently, you are missing the `dist` folder which will benefit you in later when you publish your app 👍🏽 , 

## Required Changes ♻️

- [x] Please build `npm run build` your app then commit.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by blessedjasonmwanza** [comment]
Hello @od-c0d3r ,
Thank you a lot for this insightful review. I am on to making the suggested changes right now.

> HappyCoding 🤓 👨🏽‍💻

**Review by mikethreels — APPROVED** [review]
Hi Blessed, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by blessedjasonmwanza** [comment]
Hello  @mikethreels,

> Thank you a lot for your awesome review. 😃 😍 

_going to make that merge right away 🏃🏽 ._

> #HappyHacking 👨🏽‍💻

**Pull request merged**
